### ISSUE TITLE
Gang management API

### ISSUE THREAD

**Issue by FoksVHox** [SaimorIVS/Stavox-Tablet-App-Boilerplate#2]
# It would be nice if we could manage gangs through tablet apps

### How it should work
If the active user has the permissions to kick, Invite and edit the rank then the user should be able to use those permissions just like the in-game gang menu.

**Comment by emoyly** [comment]
no

**Comment by FoksVHox** [comment]
I think the API should be able to check the current XP, the XP until the next level, amount of slots in the gang, amount of unused/used slots, the upgrades that the gang have unlocked, and available upgrades that is not unlocked.

**Comment by FoksVHox** [comment]
Additionally things to the Gang Management API that would be nice to have: 
* Current XP
* Current XP until next level
* Required XP for the next level
* The level of the gang
* Unlocked upgrades 
* Locked upgrades
* When the gang was created (idk, why but it could be used for some cool things I imagine)
* The gang’s rank of the week
* The gang’s rank of the strongest gangs
* The weeks the gangs have won
* The thing won from the won weeks
* Radio towers that the gang have the control of

**Comment by emoyly** [comment]
Would be too complicated for the very limited use-case it would have
