### ISSUE TITLE
Addition to getPlayerDataFromSteamID

### ISSUE THREAD

**Issue by FoksVHox** [SaimorIVS/Stavox-Tablet-App-Boilerplate#8]
### How it works currently
Right now you're are getting this information:

- SteamID
- Name
- Rank
- VIP
- Gang ID
- success

### The function with my addition
The function should return if the SteamID on the player is online, so the result would be this
- SteamID
- Name
- Rank
- VIP
- Gang ID
- Online 
- success

**Comment by emoyly** [comment]
Will look into adding as soon as i have time

**Comment by emoyly** [comment]
The function will now return an additional ServerID in the JSON response.
